/*
 * Exported with nin10kit v1.7
 * Time-stamp: Tuesday 11/20/2018, 20:13:55
 * 
 * Image Information
 * -----------------
 * /cs2110/host/src/images/sources/BACKGROUND_CONTROL_SCREEN.png 240@160
 * /cs2110/host/src/images/sources/BACKGROUND_END_SCREEN.png 240@160
 * /cs2110/host/src/images/sources/BACKGROUND_INSTRUCTION_SCREEN.png 240@160
 * /cs2110/host/src/images/sources/BACKGROUND_START_SCREEN.png 240@160
 * 
 * All bug reports / feature requests are to be filed here https://github.com/TricksterGuy/nin10kit/issues
 */

#ifndef BACKGROUND_H
#define BACKGROUND_H

extern const unsigned short BACKGROUND_CONTROL_SCREEN[38400];
#define BACKGROUND_CONTROL_SCREEN_SIZE 76800
#define BACKGROUND_CONTROL_SCREEN_LENGTH 38400
#define BACKGROUND_CONTROL_SCREEN_WIDTH 240
#define BACKGROUND_CONTROL_SCREEN_HEIGHT 160

extern const unsigned short BACKGROUND_END_SCREEN[38400];
#define BACKGROUND_END_SCREEN_SIZE 76800
#define BACKGROUND_END_SCREEN_LENGTH 38400
#define BACKGROUND_END_SCREEN_WIDTH 240
#define BACKGROUND_END_SCREEN_HEIGHT 160

extern const unsigned short BACKGROUND_INSTRUCTION_SCREEN[38400];
#define BACKGROUND_INSTRUCTION_SCREEN_SIZE 76800
#define BACKGROUND_INSTRUCTION_SCREEN_LENGTH 38400
#define BACKGROUND_INSTRUCTION_SCREEN_WIDTH 240
#define BACKGROUND_INSTRUCTION_SCREEN_HEIGHT 160

extern const unsigned short BACKGROUND_START_SCREEN[38400];
#define BACKGROUND_START_SCREEN_SIZE 76800
#define BACKGROUND_START_SCREEN_LENGTH 38400
#define BACKGROUND_START_SCREEN_WIDTH 240
#define BACKGROUND_START_SCREEN_HEIGHT 160

#endif

